### PR TITLE
ENH: Update CI configuration to 5.3.0 latest

### PR DESCRIPTION
**Pull request by thewtex**
ITKRemoteModuleBuildTestPackageAction main 2023-01-03.

### CODE REVIEW

**Review by tbirdso — CHANGES_REQUESTED** [review]
Please update to ITKRemoteModuleBuildTestPackageAction 1-3-2023 (instead of ITKPythonPackage)

https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/commit/a1cf940d0445ea3ea633a8d03c92cf35b7caae14

**Comment by thewtex** [comment]
@tbirdso yes!

**Review by tbirdso — APPROVED** [review]
Thanks!

**Review by PranjalSahu — APPROVED** [review]
LGTM

**Pull request merged**
